export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const SET_INGREDIANTS = 'SET_INGREDIANTS';
export const FATCH_INGREDIANS_FAILED = 'FATCH_INGREDIANS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FATCH_ORDERS_START = 'FATCH_ORDERS_START';
export const FATCH_ORDERS_SUCCESS = 'FATCH_ORDERS_SUCCESS';
export const FATCH_ORDERS_FAIL = 'FATCH_ORDERS_FAIL';